"use client";

import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useLang } from "@/lib/i18n/LanguageProvider";
import type { OfferingBundle } from "@/lib/capital/types";
import styles from "./profile.module.css";

type Form = {
  offeringId: string; shareClassId: string; jurisdiction: "ontario" | "turkey-cross-border";
  firstName: string; lastName: string; email: string; phone: string; city: string;
  objective: string; horizon: string; riskTolerance: string; lossCapacity: string; liquidityNeed: string; experience: string; intendedAmount: string; accountPreference: string;
  accreditedIncome: boolean; accreditedFinancialAssets: boolean; accreditedNetAssets: boolean; eligibleIncome: boolean; eligibleNetAssets: boolean; priorOmAmount: string;
  contactConsent: boolean; accuracyConsent: boolean;
};

export function InvestorProfile({ offerings }: { offerings: OfferingBundle[] }) {
  const params = useSearchParams(); const { lang } = useLang(); const tr = lang === "tr";
  const initialOffering = offerings.find((o) => o.slug === params.get("offering")) ?? offerings[0];
  const [step, setStep] = useState(0); const [status, setStatus] = useState<"idle"|"sending"|"success"|"error">("idle"); const [result, setResult] = useState<{ preliminaryCategory: string; warnings: string[] }>();
  const [form, setForm] = useState<Form>({ offeringId: initialOffering.id, shareClassId: params.get("shareClass") ?? initialOffering.shareClasses[0]?.id ?? "", jurisdiction: "ontario", firstName:"",lastName:"",email:"",phone:"",city:"",objective:"Balanced income and growth",horizon:"5+ years",riskTolerance:"Moderate",lossCapacity:"Some loss",liquidityNeed:"Low",experience:"Some private market experience",intendedAmount:"$25k-$100k",accountPreference:"Non-registered",accreditedIncome:false,accreditedFinancialAssets:false,accreditedNetAssets:false,eligibleIncome:false,eligibleNetAssets:false,priorOmAmount:"$0",contactConsent:false,accuracyConsent:false });
  const offering = offerings.find((o) => o.id === form.offeringId) ?? offerings[0];
  useEffect(() => { try { const saved = localStorage.getItem("hunter-capital-readiness"); if (saved) setForm((current) => ({ ...current, ...JSON.parse(saved) })); } catch {} }, []);
  useEffect(() => { try { localStorage.setItem("hunter-capital-readiness", JSON.stringify(form)); } catch {} }, [form]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function chooseOffering(id: string) { const next = offerings.find((o) => o.id === id)!; setForm((current) => ({ ...current, offeringId:id, shareClassId:next.shareClasses[0]?.id ?? "" })); }
  async function submit(event: FormEvent) { event.preventDefault(); setStatus("sending"); const response = await fetch("/api/investor-readiness", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(form) }); if (response.ok) { const data = await response.json(); setResult(data); setStatus("success"); try { localStorage.removeItem("hunter-capital-readiness"); } catch {} } else setStatus("error"); }
  const stepNames = tr ? ["Yatırım","Bölge","Hedefler","Uygunluk","İletişim"] : ["Offering","Jurisdiction","Goals","Eligibility","Contact"];
  return <main className={styles.page}>
    <aside><p>{tr ? "Yatırımcı Hazırlık Profili" : "Investor readiness profile"}</p><h1>{tr ? "Sizinle doğru görüşmeye hazırlık." : "Prepare for the right conversation."}</h1><ol>{stepNames.map((name,i) => <li key={name} className={i === step ? styles.active : i < step ? styles.done : ""}><span>{i < step ? "✓" : i + 1}</span>{name}</li>)}</ol><div><strong>{offering.shortName[lang]}</strong><small>{offering.manager.name[lang]}</small></div></aside>
    <form onSubmit={submit}>
      <header><span>{tr ? "Adım" : "Step"} {step + 1} / {stepNames.length}</span><b>{Math.round(((step+1)/stepNames.length)*100)}%</b></header>
      {step === 0 && <section><p>{tr ? "Önce değerlendirmek istediğiniz fonu seçin." : "First, choose the fund you want to evaluate."}</p><div className={styles.offerChoices}>{offerings.map((item) => <button type="button" key={item.id} className={item.id === form.offeringId ? styles.selected : ""} onClick={() => chooseOffering(item.id)}><span>{item.manager.headquarters.city}</span><strong>{item.shortName[lang]}</strong><small>{item.summary[lang]}</small></button>)}</div><label><span>{tr ? "Pay sınıfı" : "Share class"}</span><select value={form.shareClassId} onChange={(e) => update("shareClassId",e.target.value)}>{offering.shareClasses.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></section>}
      {step === 1 && <section><p>{tr ? "Kurallar ikamet ve yatırım yoluna göre değişir." : "The review path changes with residence and investing jurisdiction."}</p><div className={styles.jurisdictions}><button type="button" className={form.jurisdiction === "ontario" ? styles.selected : ""} onClick={() => update("jurisdiction","ontario")}><strong>Ontario</strong><small>{tr ? "Ön uygunluk sınıflandırması" : "Preliminary exemption classification"}</small></button><button type="button" className={form.jurisdiction === "turkey-cross-border" ? styles.selected : ""} onClick={() => update("jurisdiction","turkey-cross-border")}><strong>{tr ? "Türkiye / Sınır Ötesi" : "Turkey / Cross-border"}</strong><small>{tr ? "Her zaman manuel inceleme" : "Always requires manual review"}</small></button></div><label><span>{tr ? "Şehir" : "City"}</span><input required value={form.city} onChange={(e) => update("city",e.target.value)} /></label></section>}
      {step === 2 && <section><p>{tr ? "Bu bilgiler uygunluk değildir; görüşmenin kapsamını belirler." : "These inputs do not establish eligibility; they prepare the suitability conversation."}</p><div className={styles.grid}>{[["objective","Investment objective",["Income","Growth","Balanced income and growth","Capital preservation"]],["horizon","Time horizon",["1-3 years","3-5 years","5+ years"]],["riskTolerance","Risk comfort",["Conservative","Moderate","Growth-oriented","Unsure"]],["lossCapacity","Capacity for loss",["Limited loss","Some loss","Significant loss","Unsure"]],["liquidityNeed","Liquidity need",["High","Moderate","Low"]],["experience","Investment experience",["New to private markets","Some private market experience","Experienced private market investor"]],["intendedAmount","Intended amount",["Under $10k","$10k-$25k","$25k-$100k","$100k+"]],["accountPreference","Account preference",["Non-registered","Registered account","Corporate/entity","Unsure"]]].map(([key,label,options]) => <label key={key as string}><span>{label as string}</span><select value={form[key as keyof Form] as string} onChange={(e) => update(key as keyof Form,e.target.value as never)}>{(options as string[]).map(o => <option key={o}>{o}</option>)}</select></label>)}</div></section>}
      {step === 3 && <section><p>{form.jurisdiction === "ontario" ? (tr ? "Uygulanabilecek testleri seçin. Belgeli doğrulama daha sonra yapılır." : "Select any tests that may apply. Documentary verification happens later.") : (tr ? "Sınır ötesi yatırım otomatik sınıflandırılmaz." : "Cross-border investors are not automatically classified.")}</p>{form.jurisdiction === "ontario" ? <div className={styles.checks}>{[["accreditedIncome","Accredited income test may apply"],["accreditedFinancialAssets","Over $1M in qualifying financial assets may apply"],["accreditedNetAssets","$5M net-assets test may apply"],["eligibleIncome","Eligible-investor income test may apply"],["eligibleNetAssets","Over $400k eligible net-assets test may apply"]].map(([key,label]) => <label key={key}><input type="checkbox" checked={form[key as keyof Form] as boolean} onChange={(e) => update(key as keyof Form,e.target.checked as never)} /><span>{label}</span></label>)}<label><span>OM investments in preceding 12 months</span><select value={form.priorOmAmount} onChange={(e) => update("priorOmAmount",e.target.value)}><option>$0</option><option>Under $10k</option><option>$10k-$30k</option><option>Over $30k</option></select></label></div> : <div className={styles.notice}><strong>{tr ? "Manuel sınır ötesi inceleme" : "Manual cross-border review"}</strong><p>{tr ? "Kanada ve Türkiye kuralları, vergi ikameti, ürün izni, AML, fon kaynağı ve para transferi birlikte incelenmelidir." : "Canadian and Turkish rules, tax residence, product permissions, AML, source of funds, and currency transfer must be reviewed together."}</p></div>}</section>}
      {step === 4 && <section><p>{tr ? "Bir sonraki adım yatırım talimatı değil, lisanslı bir görüşmedir." : "The next step is a licensed conversation, not an investment instruction."}</p><div className={styles.grid}><label><span>First name</span><input required value={form.firstName} onChange={(e) => update("firstName",e.target.value)} /></label><label><span>Last name</span><input required value={form.lastName} onChange={(e) => update("lastName",e.target.value)} /></label><label><span>Email</span><input required type="email" value={form.email} onChange={(e) => update("email",e.target.value)} /></label><label><span>Phone</span><input value={form.phone} onChange={(e) => update("phone",e.target.value)} /></label></div><div className={styles.checks}><label><input required type="checkbox" checked={form.contactConsent} onChange={(e) => update("contactConsent",e.target.checked)} /><span>{tr ? "Hunter Group Capital'ın bu profil hakkında benimle iletişime geçmesini kabul ediyorum." : "I consent to Hunter Group Capital contacting me about this profile."}</span></label><label><input required type="checkbox" checked={form.accuracyConsent} onChange={(e) => update("accuracyConsent",e.target.checked)} /><span>{tr ? "Bunun ön değerlendirme olduğunu, onay veya yatırım talimatı olmadığını anlıyorum." : "I understand this is preliminary, not an approval or investment instruction."}</span></label></div>{status === "success" && result ? <div className={styles.result}><strong>{result.preliminaryCategory.replaceAll("-"," ")}</strong>{result.warnings.map(w => <p key={w}>{w}</p>)}</div> : <button className={styles.submit} disabled={status === "sending"}>{status === "sending" ? "Submitting…" : (tr ? "Profili incelemeye gönder" : "Submit for review")}</button>}{status === "error" && <p className={styles.error}>Unable to submit. Please review the form and try again.</p>}</section>}
      <footer><button type="button" disabled={step === 0 || status === "success"} onClick={() => setStep(s => s-1)}>← {tr ? "Geri" : "Back"}</button>{step < 4 && <button type="button" onClick={() => setStep(s => s+1)}>{tr ? "Devam" : "Continue"} →</button>}</footer>
    </form>
  </main>;
}
