#!/usr/bin/env python3
"""Regenerate shared Codex/Cowork posting artifacts from repo source files."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SKILL_ROOT = REPO_ROOT / ".agents" / "skills" / "jack-ve-tara-posting"
REFERENCES = SKILL_ROOT / "references"
OUTPUT_ROOT = REPO_ROOT / "shared-agent" / "generated"

SKILL_FILE = SKILL_ROOT / "SKILL.md"
VOICE_FILE = REFERENCES / "voice.md"
TURKISH_FILE = REFERENCES / "turkish-characters.md"

SOURCE_FILES = [
    SKILL_FILE,
    VOICE_FILE,
    TURKISH_FILE,
]


@dataclass(frozen=True)
class Platform:
    name: str
    slug: str
    reference: Path
    account: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def extract_platform_order(skill_text: str) -> list[str]:
    match = re.search(
        r"Generate the Gate 1 copy package in this order:\s*([^\n]+)",
        skill_text,
    )
    if not match:
        raise ValueError("Could not find platform order in posting SKILL.md")
    return [item.strip().rstrip(".") for item in match.group(1).split(",")]


def extract_account(reference_text: str, platform_name: str) -> str:
    match = re.search(r"^Account:\s*(.+)$", reference_text, re.MULTILINE)
    if not match:
        raise ValueError(f"Could not find Account line for {platform_name}")
    return match.group(1).strip()


def load_platforms() -> list[Platform]:
    skill_text = read_text(SKILL_FILE)
    platforms: list[Platform] = []
    for name in extract_platform_order(skill_text):
        slug = name.lower()
        reference = REFERENCES / f"{slug}.md"
        if not reference.exists():
            raise FileNotFoundError(f"Missing platform reference: {reference}")
        account = extract_account(read_text(reference), name)
        platforms.append(Platform(name=name, slug=slug, reference=reference, account=account))
    return platforms


def source_files(platforms: list[Platform]) -> list[Path]:
    files = [*SOURCE_FILES, *(platform.reference for platform in platforms)]
    return sorted(dict.fromkeys(files), key=lambda path: path.as_posix())


def source_digest(platforms: list[Platform]) -> dict[str, object]:
    files = source_files(platforms)
    return {
        "schema_version": 1,
        "source_root": ".agents/skills/jack-ve-tara-posting",
        "files": [
            {
                "path": path.relative_to(REPO_ROOT).as_posix(),
                "sha256": sha256(path),
            }
            for path in files
        ],
    }


def extract_code_block_after_heading(text: str, heading: str) -> str:
    heading_index = text.find(heading)
    if heading_index == -1:
        raise ValueError(f"Could not find heading: {heading}")
    after_heading = text[heading_index:]
    match = re.search(r"```(?:text)?\n(.*?)\n```", after_heading, re.DOTALL)
    if not match:
        raise ValueError(f"Could not find code block after heading: {heading}")
    return match.group(1).strip()


def generated_header(kind: str) -> str:
    return (
        f"<!-- Generated by tools/refresh_agent_bundles.py. Do not edit by hand. -->\n"
        f"<!-- {kind} reads source truth from .agents/skills/jack-ve-tara-posting. -->\n"
    )


def markdown_platform_table(platforms: list[Platform]) -> str:
    lines = ["| Platform | Account | Source file |", "|---|---|---|"]
    for platform in platforms:
        source = platform.reference.relative_to(REPO_ROOT).as_posix()
        lines.append(f"| {platform.name} | `{platform.account}` | `{source}` |")
    return "\n".join(lines)


def render_codex_bundle(platforms: list[Platform]) -> str:
    return (
        generated_header("Codex/Atlas bundle")
        + """# Jack ve Tara Shared Posting Agent — Codex/Atlas

This is a thin generated wrapper. The canonical workflow, handles, voice rules, platform rules, and Turkish-character protocol live in `.agents/skills/jack-ve-tara-posting`. At the start of every run, read that skill and its references fresh.

## Required Runtime Reads

1. Read `.agents/skills/jack-ve-tara-posting/SKILL.md`.
2. Read `.agents/skills/jack-ve-tara-posting/references/voice.md`.
3. Before staging or posting, read `.agents/skills/jack-ve-tara-posting/references/turkish-characters.md`.
4. Read every platform reference when no platform is excluded.

## Current Platform Order And Accounts

"""
        + markdown_platform_table(platforms)
        + """

## Posting Workflow

1. Require a video filename or explicit path. Never choose the newest video automatically.
2. Generate Gate 1 copy in the platform order above.
3. Treat `go` as approval to stage only.
4. Stage through signed-in ChatGPT Atlas using Codex Computer Use and the existing signed-in platform tab when available.
5. For local videos, select the file with the native macOS file picker from Downloads or the requested folder.
6. Use Chrome automation only as a verification helper for page state, paste, and exact Turkish read-back, not as the primary local-video upload path when Atlas native selection is available.
7. Enter Turkish copy only by UTF-8 clipboard paste. Do not simulate Turkish keystrokes.
8. Read each composer back and compare it character-for-character against approved copy before Gate 2.
9. Show Gate 2 staging summary. Include account, video upload state, and Turkish read-back status per platform.
10. Publish only after Jack says `publish all`, with 1 to 2 minutes between platforms.

## Hard Stops

Stop on passwords, 2FA, passkeys, CAPTCHAs, account checkpoints, unexpected account switchers, or missing upload permissions. Do not work around those screens.
"""
    )


def render_cowork_bundle(platforms: list[Platform]) -> str:
    return (
        generated_header("Cowork/Claude-in-Chrome bundle")
        + """# Jack ve Tara Shared Posting Agent — Cowork/Claude-in-Chrome

This is a thin generated loader, not a second source of truth. Pull or read the GitHub repo at run start, then load `.agents/skills/jack-ve-tara-posting` and follow those files exactly.

## Step 0: Sync Source

Use the public repo `https://github.com/jackhunterking/jack-ve-tara-codex` as the source of truth. Before generating or staging, make sure the local copy is on current `main`, then read:

- `.agents/skills/jack-ve-tara-posting/SKILL.md`
- `.agents/skills/jack-ve-tara-posting/references/voice.md`
- `.agents/skills/jack-ve-tara-posting/references/turkish-characters.md`
- All platform references unless Jack explicitly excludes platforms.

Do not copy handles, platform rules, voice rules, or Turkish-character rules into a separate editable Claude project. This bundle only points to the repo files.

## Current Platform Order And Accounts

"""
        + markdown_platform_table(platforms)
        + """

## Posting Workflow

1. Require a video filename or explicit path. If Jack gives only a filename, search likely locations to confirm that exact filename. Never pick the newest video automatically.
2. Generate Gate 1 copy for all seven platforms unless Jack excludes platforms.
3. Treat `go` as staging approval only.
4. Stage through signed-in Chrome/Cowork tabs.
5. Enter Turkish copy only with `document.execCommand("insertText", false, TEXT)` or UTF-8 clipboard paste. Never type Turkish character by character.
6. Read the composer value/page content back and compare it character-for-character against approved copy before Gate 2.
7. Show Gate 2 staging summary. Include Turkish read-back status per platform.
8. Publish only after Jack says `publish all`, with 1 to 2 minutes between platforms.

## Hard Stops

Stop on passwords, 2FA, passkeys, CAPTCHAs, account checkpoints, unexpected account switchers, or missing upload permissions. Do not work around those screens.
"""
    )


def render_control_panel(platforms: list[Platform]) -> str:
    turkish_text = read_text(TURKISH_FILE)
    canary = extract_code_block_after_heading(turkish_text, "Quick self-test string")
    platform_rows = "\n".join(
        f"<tr><td>{html.escape(platform.name)}</td><td>{html.escape(platform.account)}</td><td>{html.escape(platform.reference.relative_to(REPO_ROOT).as_posix())}</td></tr>"
        for platform in platforms
    )
    platform_checkboxes = "\n".join(
        f'<label><input type="checkbox"> {html.escape(platform.name)} staged, Turkish read-back passed</label>'
        for platform in platforms
    )
    return (
        generated_header("Posting Control panel")
        + f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Jack ve Tara Posting Control</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #17202a;
      --muted: #52616f;
      --line: #d6dde3;
      --panel: #f7f9fb;
      --accent: #006b5f;
      --danger: #9b1c31;
    }}
    body {{
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--ink);
      background: white;
      line-height: 1.45;
    }}
    main {{
      max-width: 980px;
      margin: 0 auto;
      padding: 32px 20px 48px;
    }}
    h1, h2 {{
      letter-spacing: 0;
    }}
    h1 {{
      margin: 0 0 6px;
      font-size: 32px;
    }}
    h2 {{
      margin-top: 30px;
      font-size: 20px;
    }}
    p {{
      margin: 8px 0;
    }}
    .note {{
      color: var(--muted);
    }}
    .warning {{
      color: var(--danger);
      font-weight: 700;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin-top: 12px;
    }}
    th, td {{
      border: 1px solid var(--line);
      padding: 10px;
      text-align: left;
      vertical-align: top;
    }}
    th {{
      background: var(--panel);
    }}
    code, pre {{
      font-family: "SFMono-Regular", Consolas, monospace;
    }}
    pre {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 6px;
      padding: 12px;
      overflow-x: auto;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 14px;
    }}
    .panel {{
      border: 1px solid var(--line);
      border-radius: 6px;
      padding: 14px;
      background: var(--panel);
    }}
    label {{
      display: block;
      margin: 8px 0;
    }}
  </style>
</head>
<body>
  <main>
    <h1>Jack ve Tara Posting Control</h1>
    <p class="note">Canonical template generated from <code>.agents/skills/jack-ve-tara-posting</code>. Do not edit this HTML by hand.</p>

    <h2>Source Of Truth</h2>
    <p>Before each run, pull or read <code>https://github.com/jackhunterking/jack-ve-tara-codex</code> and load the posting skill plus references fresh.</p>
    <p class="warning">No downstream panel, plugin, or schedule should keep its own editable handles, platform rules, voice rules, or Turkish rules.</p>

    <h2>Platforms</h2>
    <table>
      <thead><tr><th>Order</th><th>Account</th><th>Source file</th></tr></thead>
      <tbody>
        {platform_rows}
      </tbody>
    </table>

    <h2>Gate 1</h2>
    <div class="panel">
      <label><input type="checkbox"> Video filename or explicit path confirmed</label>
      <label><input type="checkbox"> No newest-video guessing used</label>
      <label><input type="checkbox"> Copy generated for requested platforms in the order above</label>
      <label><input type="checkbox"> Jack approved copy with edits or <code>go</code></label>
    </div>

    <h2>Gate 2</h2>
    <div class="panel">
      {platform_checkboxes}
      <label><input type="checkbox"> Atlas native file selection used for local videos when available</label>
      <label><input type="checkbox"> Account, selected file, and upload state confirmed on every platform</label>
      <label><input type="checkbox"> Staging summary shown to Jack</label>
      <label><input type="checkbox"> Publishing held until exact phrase <code>publish all</code></label>
    </div>

    <h2>Turkish Canary</h2>
    <pre>{html.escape(canary)}</pre>
    <p>Codex/Atlas: paste from UTF-8 clipboard. Cowork/Claude-in-Chrome: use <code>document.execCommand("insertText", false, TEXT)</code> or UTF-8 clipboard paste. Both must read back and compare exactly before Gate 2.</p>
    <p>Local-video uploads should use Atlas desktop control and the native macOS file picker when available. Chrome automation should stay a verification helper for page state and exact text checks.</p>

    <h2>Hard Stops</h2>
    <p>Stop on passwords, 2FA, passkeys, CAPTCHAs, account checkpoints, unexpected account switchers, or missing upload permissions.</p>
  </main>
</body>
</html>
"""
    )


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report whether generated artifacts are current without writing")
    args = parser.parse_args()

    platforms = load_platforms()
    outputs = {
        OUTPUT_ROOT / "codex-atlas-posting.md": render_codex_bundle(platforms),
        OUTPUT_ROOT / "cowork-claude-chrome-posting.md": render_cowork_bundle(platforms),
        OUTPUT_ROOT / "posting-control.html": render_control_panel(platforms),
        OUTPUT_ROOT / "source-digest.json": json.dumps(source_digest(platforms), indent=2, ensure_ascii=False) + "\n",
    }

    stale = [path for path, content in outputs.items() if not path.exists() or read_text(path) != content]
    if args.check:
        if stale:
            print("Generated artifacts are stale:")
            for path in stale:
                print(f"- {path.relative_to(REPO_ROOT).as_posix()}")
            return 1
        print("Generated artifacts are current.")
        return 0

    for path, content in outputs.items():
        write(path, content)

    print("Refreshed shared posting artifacts:")
    for path in outputs:
        print(f"- {path.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
